### ISSUE TITLE
Feeding in data mostly done

### ISSUE THREAD

**Issue by Bdreon** [Bdreon/xhamster-project#1]
I have fed in the data and pushed the changes, but have not pushed the output file as it was 120mb. I also uploaded the supplemental dataset I mentioned in class just so I could look at it in my initial analysis, but will work on recoding the tags in the main dataset, so it should wind up superfluous once that is finished.

**Comment by AaronGullickson** [comment]
@Bdreon Looks good so far. Two things:

1. You don't need to write out the data yet. The `organize_data.R` script will eventually organize your data into a much smaller analytical dataset that you can **then** read out and push to GH.
2. Don't forget to include a description of the data in the data and methods section of the paper. You can largely use the text you already wrote for the README.
